name: Java CI with Gradle

on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MODRINTH_TOKEN: ${{ secrets.MR_API_TOKEN }}
      CURSEFORGE_TOKEN: ${{ secrets.CF_API_TOKEN }}
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
      - name: Fetch Tags
        run: git fetch --unshallow --tags
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build Artifacts with Gradle
        run: ./gradlew build
      - name: Publish to Maven
        run: ./gradlew publish
      - name: Get tag
        if: ${{ success() && startsWith(github.ref, 'refs/tags/') }}
        id: tag
        uses: dawidd6/action-get-tag@v1
      - uses: jungwinter/split@v2
        id: split
        with:
          separator: "+"
          msg: ${{steps.tag.outputs.tag}}
      - name: "Upload to Distributors"
        uses: Kir-Antipov/mc-publish@v3.3.0
        if: ${{ success() && startsWith(github.ref, 'refs/tags/') }}
        with:
          modrinth-id: 1W98a849
          modrinth-token: ${{ env.MODRINTH_TOKEN }}
          curseforge-id: 535291
          curseforge-token: ${{ env.CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

          name: "[Universal ${{steps.split.outputs._1}}] MCA Reborn - ${{steps.split.outputs._0}}"
          changelog-file: changelog.md
          version-type: release
          files: build/libs/*-@(universal).jar
          loaders: |
            fabric
            forge
            quilt
          game-versions: |
            ${{steps.split.outputs._1}}
          java: |
            Java 17
          dependencies: |
            architectury-api | depends | *
            fabric-api | recommends | *
            qsl | recommends | *

          retry-attempts: 2
          retry-delay: 10000
          fail-mode: skip